version: '3'

services:
  openvpn:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.openvpn
    image: openvpn:local
    command: /etc/openvpn/setup/configure.sh
    environment:
      OVPN_SERVER_NET: "100.0.0.0"
      OVPN_SERVER_MASK: "255.255.252.0"
      OVPN_CCD: "True"
      OVPN_CCD_PATH: "/etc/openvpn/ccd"
    cap_add:
      - NET_ADMIN
    ports:
      - 7777:1194 # for openvpn
      - 8080:8080 # for ovpn-admin because of network_mode
    volumes:
      - ./easyrsa_master:/etc/openvpn/easyrsa
      - ./ccd_master:/etc/openvpn/ccd
  ovpn-admin:
    restart: always
    build:
      context: .
    image: ovpn-admin:local
    command: /app/ovpn-admin
    environment:
      OVPN_MASTER_USER: "devops"
      OVPN_MASTER_PASSWORD: "investree123!"
      OVPN_PASSWD_AUTH: "true"
      OVPN_AUTH: "True"
      OVPN_AUTH_DB_PATH: "/mnt/easyrsa/pki/users.db"
      OVPN_DEBUG: "True"
      OVPN_VERBOSE: "True"
      OVPN_NETWORK: "100.0.0.0/22"
      EASYRSA_PATH: "/mnt/easyrsa"
      OVPN_SERVER: "8.215.32.195:7777:tcp"
      OVPN_INDEX_PATH: "/mnt/easyrsa/pki/index.txt"
      OVPN_CCD: "True"
      OVPN_CCD_PATH: "/mnt/ccd"
    network_mode: service:openvpn
    volumes:
      - ./easyrsa_master:/mnt/easyrsa
      - ./ccd_master:/mnt/ccd
